# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.4'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: TSLint
        run: npm run lint

      - name: Unit Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - run: npx webdriver-manager update
      - name: E2E Test
        run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
